name: Security Scanning

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'


jobs:
  scan-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "backend"
          path: "backend"
          format: "HTML"
        env:
          JAVA_HOME: /opt/java/openjdk


      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: depcheck-report
          path: '**/dependency-check-report.html'


  scan-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Audit NPM packages
        run: npm audit --prefix frontend --audit-level=moderate